### ISSUE TITLE
pre-commit/mirrors-prettier CI/CD hook fails - node-related crash

### ISSUE THREAD

**Issue by mlubej** [pre-commit-ci/issues#218]
Since yesterday, or perhaps a few days ago, the `mirrors-prettier` hook started failing. It's hard to pinpoint the exact issue, but I cannot reproduce the error locally.

Here is the stack trace from the gitlab CI job:

```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
    at WorkerShim.dispatchEvent (node:internal/event_target:746:13)
    at Worker.<anonymous> (file:///root/.cache/pre-commit/repot612g4x_/node_env-default/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:38:18)
    at Worker.emit (node:events:520:28)
    at [kOnErrorMessage] (node:internal/worker:319:10)
    at [kOnMessage] (node:internal/worker:330:37)
    at MessagePort.<anonymous> (node:internal/worker:231:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v22.3.0
```

Thanks!

**Comment by asottile** [comment]
this issue tracker is for https://pre-commit.ci, not prettier
