### ISSUE TITLE
pre-commit passes, pre-commit-ci fails

### ISSUE THREAD

**Issue by MarcoGorelli** [pre-commit-ci/issues#8]
xref https://github.com/nbQA-dev/nbQA/pull/377#issuecomment-717192176

pre-commit passed, but pre-commit-ci gave us
```
Fix End of Files.........................................................Passed
Fix requirements.txt.....................................................Passed
Trim Trailing Whitespace.................................................Passed
Debug Statements (Python)................................................Passed
Validate Pre-Commit Manifest.............................................Passed
black....................................................................Passed
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'please-upgrade-node'
Require stack:
- /pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js
- /pc/clone/89rCdSwwReu-UQrdqlPxWw/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js',
    '/pc/clone/89rCdSwwReu-UQrdqlPxWw/bin/prettier.js'
  ]
}

pylint...................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
pydocstyle...............................................................Passed
interrogate..............................................................Passed
mypy.....................................................................Passed
pyupgrade................................................................Passed
codespell................................................................Passed
darglint.................................................................Passed
```

The hook which fails is:
```
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        exclude: README.md
```

**Comment by asottile** [comment]
dupe #2 -- try using prettier/pre-commit instead
